### ISSUE TITLE
v1.0 board

### ISSUE THREAD

**Issue by gtalusan** [lukewakeford/DSLSwitchMod#2]
Hello, apologies for posting on GitHub -- I'm interested in purchasing a button cap and board for your 1.0 variant.  Are you selling this anywhere?  Printing out the PCB isn't a problem for me, but the 3D printer is dark magic for me at the moment.

Thanks!

**Comment by lukewakeford** [comment]
@gtalusan Hey sorry for the extremely late reply!
I have been selling a few on eBay, were you able to get hold of one yet?

**Comment by gtalusan** [comment]
No worries, I was able to figure it out.  Thanks!
